# ~/.config/yazelix/yazelix.toml

# Include optional tools like lazygit, mise, etc. (default: true)
include_optional_deps = true

# Include Yazi extensions for previews, archives, etc. (default: true)
include_yazi_extensions = true

# Build Helix from source (true) or use nixpkgs version (false). (default: true)
build_helix_from_source = false

# Default shell for Zellij: "nu" or "bash". (default: "nu")
default_shell = "nu"

# Learn more in <add link>
