# Alacritty configuration example for Yazelix
#
# This is a STATIC EXAMPLE for users with system-installed Alacritty.
# For bundled terminals, configs are generated dynamically with your yazelix settings.
# To use: cp ~/.config/yazelix/configs/terminal_emulators/alacritty/alacritty.toml ~/.config/alacritty/alacritty.toml

[general]
import = []

[env]
TERM = "xterm-256color"

[shell]
program = "bash"
args = ["-l", "-c", "nu ~/.config/yazelix/nushell/scripts/core/start_yazelix.nu"]

[window]
decorations = "None"
padding = { x = 0, y = 10 }
class = { instance = "yazelix", general = "com.yazelix.Yazelix" }

# Transparency (configurable via yazelix.nix)
opacity = 0.95

# Cursor trails: Not supported in Alacritty

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12

[colors]
# Abernathy theme colors would go here
primary = { background = "#000000", foreground = "#ffffff" }