[[mgr.append_keymap]]
on = [ "<C-y>" ]
run = "quit"
desc = "Quit Yazi (toggle with Helix)"

[[mgr.append_keymap]]
on = [ "<A-y>" ] 
run = "shell 'zellij action focus-next-pane'"
desc = "Focus next pane"
