[[mgr.append_keymap]]
on = [ "<C-y>" ]
run = "quit"
desc = "Quit Yazi (toggle with Helix)"

[[mgr.append_keymap]]
on = [ "<A-y>" ] 
run = "shell 'nu $HOME/.config/yazelix/nushell/scripts/integrations/focus_helix.nu'"
desc = "Focus Helix pane"
